### ISSUE TITLE
Issue with converting larger journals

### ISSUE THREAD

**Issue by jswantekdds** [kulapard/dayone-to-obsidian#67]
I love your program and it has worked well with converting my smaller journals.  With my larger journals, I am getting this error:

Invalid DayOne journal file: C:\dayone\jjs\Canoe.json: 301 validation errors for Journal
entries.0.photos.0.location.country
  Field required [type=missing, input_value={'timeZoneName': 'America...de': 42.726749420166016}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing

Thanks!

**Comment by kulapard** [comment]
@jswantekdds thank you for the report. Please try the 0.4.9 (or graater) version.
